name: movie_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # SQLite database plugin
  sqflite: any
  path_provider: any
  intl: ^0.17.0
  provider: ^5.0.0

  # firebase integration
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
#  cloud_firestore: ^0.14.0+2
#  firebase_storage: ^4.0.0
  image_picker:
#  shared_preferences: ^0.5.0

  # download image
#  http: ^0.12.2

  #  # firebase integration
#  firebase_core: ^1.4.0
#  cloud_firestore: ^2.4.0
#  firebase_storage: ^10.0.1
#
#  # download image
#   http: ^0.12.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf